networks:
  apps:
    external: true

services:
  signalbox-api:
    container_name: signalbox-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - apps
    env_file:
      - .env
    restart: unless-stopped